### ISSUE TITLE
All code on one line causes error

### ISSUE THREAD

**Issue by Not-A-User1059** [MyPingO/staircase-imports#2]
It shows an error (Failed to match multiline import) that from what I can tell happens whenever the entire script is on one line. This isn't an issue that affects anything, it just would be better to not have it show an error whenever this happens.

**Comment by MyPingO** [comment]
At the moment, the extension assumes your code is formmated properly. Since there are hundreds of ways to format your code and have it still work (like having all your code on one line), it's proving challenging to implement staircase imports to work perfectly. 

The error is there because it assumes your code is formatted properly, and if there is still an error, it reminds you to post an issue.

I'm in the middle of refactoring some of the code base to be more robust in how it handles its approach to formating imports. In the meantime, I can add a configuration setting to disable warning messages if you want it (though it will have to be tomorrow).

**Comment by Not-A-User1059** [comment]
> I can add a configuration setting to disable warning messages if you want it (though it will have to be tomorrow).

It's fine. I was just letting you know that I found a slight bug
